nameOverride: "prometheus"
fullnameOverride: "prometheus"

alertmanager:
  enabled: false
    
commonValue: &clusterName test
grafana:
  additionalDataSources: 
    - name: Loki
      type: loki
      isDefault: false
      access: proxy
      url: http://loki-stack:3100
      version: 1

