loki:
  isDefault: false
  nameOverride: "loki-stack"
  fullnameOverride: "loki-stack"


promtail:
  enabled: true
  config:
    logLevel: info
    serverPort: 3102
    clients:
      - url: http://loki-stack:3100/loki/api/v1/push

      
